Add posts benchmarks
dappforce/subsocial-parachain pull request #100
Opened 2022-07-07 21:26 UTC by TarekkMA

2022-12-22 09:19 UTC, F3Joule requested changes

2022-12-22 09:19 UTC, F3Joule commented on pallets/posts/src/benchmarking.rs
> +        ensure!(updated_post.hidden == true, "Post wasn't updated");
```suggestion
        ensure!(updated_post.hidden == true, "Post hidden status wasn't updated");
```

2022-12-22 09:19 UTC, F3Joule commented on pallets/posts/src/benchmarking.rs
> +        ensure!(updated_post.content == new_content, "Post wasn't updated");
```suggestion
        ensure!(updated_post.content == new_content, "Post content wasn't updated");
```

2022-12-27 14:14 UTC, F3Joule requested changes

2022-12-27 14:14 UTC, F3Joule commented on pallets/posts/Cargo.toml
>  std = [
Add `frame-benchmarking/std` to `std=[...]` to prevent silly errors in the future.

2022-12-27 14:15 UTC, F3Joule commented
Also, [this suggestion](https://github.com/dappforce/subsocial-parachain/pull/100#discussion_r1055249266) isn't resolved.

2023-01-25 14:24 UTC, F3Joule approved these changes

2023-01-25 14:30 UTC, F3Joule approved these changes

2023-01-25 14:30 UTC, F3Joule commented on pallets/posts/Cargo.toml
> +runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
```suggestion
runtime-benchmarks = ['frame-benchmarking/runtime-benchmarks']
```

2023-01-25 14:30 UTC, F3Joule commented on pallets/posts/Cargo.toml
> +try-runtime = [ "frame-support/try-runtime" ]
```suggestion
try-runtime = ['frame-support/try-runtime']
```

2023-01-25 14:30 UTC, F3Joule commented on pallets/posts/Cargo.toml
> +frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false, optional = true }
```suggestion
frame-benchmarking = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.24', default-features = false, optional = true }
```

2023-01-26 14:33 UTC, olehmell approved these changes

2023-01-26 14:47 UTC, merged