Add sudo calls to migrate data in spaces and space-follows pallets
dappforce/subsocial-parachain pull request #119
Opened 2022-07-21 09:25 UTC by F3Joule

2022-07-26 15:32 UTC, siman approved these changes

2022-07-27 17:48 UTC, TarekkMA requested changes

2022-07-27 17:48 UTC, TarekkMA commented on pallets/spaces/src/lib.rs
> +            Ok(())
Add Pays::No

2022-07-27 17:48 UTC, TarekkMA commented on pallets/spaces/src/lib.rs
> +            Ok(())
Add Pays::No

2022-07-28 14:17 UTC, TarekkMA approved these changes

2022-07-28 14:17 UTC, TarekkMA commented on pallets/space-follows/src/lib.rs
> +
Can we use `HashSet` instead of `Vec`, so we can avoid duplicates.

2022-07-28 14:17 UTC, TarekkMA commented on pallets/spaces/src/lib.rs
> +            SpaceIdsByOwner::<T>::mutate(&owner, |ids| {
See if we can use `HashSet`

2022-08-03 15:12 UTC, siman approved these changes

2022-08-03 15:13 UTC, merged