Add create_space_as_profile extrinsic
dappforce/subsocial-parachain pull request #153
Opened 2022-10-20 10:44 UTC by F3Joule

Based on #152

2022-11-04 15:24 UTC, F3Joule commented
Everything works fine except that we have an issue with running tests from time to time: `mockall` affects a few tests results when it breaks, but tests themselves work fine.

2023-01-06 15:22 UTC, siman commented
Let's delete this unused func:

```rust
        fn try_set_profile(account: &T::AccountId, space_id: SpaceId) -> DispatchResult {
            Self::do_set_profile(account, space_id)
        }
```

2023-01-06 17:55 UTC, siman requested changes

2023-01-06 18:05 UTC, siman approved these changes

2023-01-12 09:52 UTC, olehmell approved these changes

2023-01-12 10:00 UTC, TarekkMA approved these changes

2023-01-30 12:56 UTC, merged