Improve domains pallet
dappforce/subsocial-parachain pull request #162
Opened 2022-12-02 11:10 UTC by F3Joule

checklist tbd.

2022-12-13 15:00 UTC, TarekkMA requested changes

2022-12-13 16:31 UTC, siman requested changes

2022-12-14 12:58 UTC, F3Joule commented on pallets/domains/src/types.rs
> +/// Is a domain name vector.
Yeah, sounds more descripting. Waiting for Beef to approve or to propose another variant.

2022-12-14 13:00 UTC, F3Joule commented on pallets/domains/src/types.rs
> +pub(crate) struct DomainData<T: Config> {
note: it's an internal sturcture (not exposed out of pallet), used not to pass too many arguments to a function, so replaced them with this struct.

2022-12-14 13:03 UTC, F3Joule commented on runtime/src/lib.rs
> +	type ManagerOrigin = EnsureRoot<AccountId>;
I prefer `ForceOrigin` as it's oftenly used in Substrate FRAME pallets, e.g. [identity](https://github.dev/paritytech/substrate/blob/3e7e33def47bb383a90d0caa6755229d7e402c4d/bin/node/runtime/src/lib.rs#L1261), [assets](https://github.dev/paritytech/substrate/blob/3e7e33def47bb383a90d0caa6755229d7e402c4d/bin/node/runtime/src/lib.rs#L1371), [uniques](https://github.dev/paritytech/substrate/blob/3e7e33def47bb383a90d0caa6755229d7e402c4d/bin/node/runtime/src/lib.rs#L1371).

2022-12-14 13:13 UTC, F3Joule commented on pallets/domains/src/lib.rs
> +        type Currency: ReservableCurrency<Self::AccountId> + Currency<Self::AccountId>;
No, actually there's no inheritance.
[Currency trait](https://paritytech.github.io/substrate/master/frame_support/traits/tokens/currency/trait.Currency.html) has no `reserve` and `unreserve` functions in it, but [ReservableCurrency](https://paritytech.github.io/substrate/master/frame_support/traits/trait.ReservableCurrency.html) has.

2022-12-14 13:53 UTC, TarekkMA commented on pallets/domains/src/lib.rs
> +        type Currency: ReservableCurrency<Self::AccountId> + Currency<Self::AccountId>;
I mean that `ReservableCurrency` has all that in `Currency`

2022-12-14 21:02 UTC, Yung-Beef reviewed
You should start commenting your code more if we hope to have 3rd party Substrate devs someday

2022-12-14 21:02 UTC, Yung-Beef commented on runtime/src/lib.rs
> +	type MaxPriceRanges = ConstU32<10>;
Yeah it might read like the maximum price.. MaxCountOfPriceRanges is the best option as far as I can tell

2022-12-15 11:44 UTC, F3Joule commented on pallets/domains/src/mock.rs
>      pub static ReservationPeriodLimit: BlockNumber = 0;
Yes. This is a limit that indicates the maximum period for which you can purchase\reserve a domain.

2022-12-15 12:19 UTC, F3Joule commented on pallets/domains/src/mock.rs
> +    pub static InitialPriceRanges: Vec<(PriceRangeStart, Balance)> = Vec::new();
Multiple

2022-12-15 12:23 UTC, F3Joule commented on pallets/domains/src/mock.rs
>  pub(crate) const DUMMY_ACCOUNT: u64 = 2;
That's for testing purposes only. This account should be used in tests, where we don't care about account, want to check something different, but need not only `DOMAIN_OWNER` account, but some another one, which's not permitted to do any actions regarding domain, which `DOMAIN_OWNER` had registered.

2022-12-15 12:32 UTC, F3Joule commented on pallets/domains/src/mock.rs
>  pub(crate) fn account_with_balance(id: AccountId, balance: Balance) -> AccountId {
Yeah, while I was looking through previous suggestion, I noticed that it's a bit confusing to use 2 functions. I'll refactor this.

2022-12-15 12:35 UTC, F3Joule commented on pallets/domains/src/mock.rs
>      pub(crate) fn reservation_period_limit(mut self, reservation_period_limit: BlockNumber) -> Self {
Yeah, definitely makes sense to make all these functions to have prefix `set_` as Rust naming convention says.
Just used to name tham simillary to how the constants are named. This function just mock some pallet configuration's constant for a specific tests.

2022-12-15 13:07 UTC, F3Joule commented on pallets/domains/src/types.rs
> +    pub fn new(
It's a simple constructor for a structure. We use [here(1)](https://github.com/dappforce/subsocial-parachain/blob/7c7a25468c2ca5b66c8c59b9579dcb1c492f1645/pallets/domains/src/lib.rs#L257) and [here(2)](https://github.com/dappforce/subsocial-parachain/blob/7c7a25468c2ca5b66c8c59b9579dcb1c492f1645/pallets/domains/src/lib.rs#L278).

2022-12-15 13:09 UTC, F3Joule commented on runtime/src/lib.rs
> +	pub DefaultPricesSet: Vec<(PriceRangeStart, Balance)> = vec![
"Set" here is a noun. A set of default prices in accordance with the domain length range.

2022-12-15 14:40 UTC, F3Joule commented on pallets/domains/src/mock.rs
>      pub const DomainsInsertLimit: u32 = 2860;
A limit for inserting reserved domain names.

2022-12-15 14:43 UTC, F3Joule commented on pallets/domains/src/tests.rs
> +                Error::<Test>::InsufficientBalanceToReserveDeposit,
Domain deposit.
It's already to long error name. I'd like to change it to `UnableToReserveDomainDeposit` - how is this one?

2022-12-16 11:44 UTC, TarekkMA requested changes

2022-12-16 14:58 UTC, F3Joule commented on pallets/domains/src/lib.rs
Why it looks good now is because we don't allow more than second-level domains:
"tarek.sub" and that's it, no more levels allowed.

2022-12-16 14:59 UTC, F3Joule commented on pallets/domains/src/mock.rs
> +pub(super) fn set_account_balance_as(account: &AccountId, balance: Balance) {
Just followed Beef's suggestion. It was like this before.

2022-12-16 16:44 UTC, Yung-Beef commented on pallets/domains/src/mock.rs
>      pub const DomainsInsertLimit: u32 = 2860;
Maybe just make sure to comment that, I can't think of a better name that won't be super long

2022-12-16 16:46 UTC, Yung-Beef commented on pallets/domains/src/mock.rs
> +pub(super) fn set_account_balance_as(account: &AccountId, balance: Balance) {
> what about renaming it to be `make_free_balance_be`

The meaning is the same, but set account balance as is more correct English

2022-12-16 16:49 UTC, Yung-Beef commented on pallets/domains/src/tests.rs
> +                Error::<Test>::InsufficientBalanceToReserveDeposit,
NeedMoreTokensToReserveDomain
TooPoorForDomainReservation haha
BalanceTooLowToReserveDomain
BalanceTooLowForReservation
NeedMoreTokensForReservation

2022-12-23 13:01 UTC, olehmell approved these changes

2022-12-24 17:22 UTC, siman requested changes

2022-12-28 09:17 UTC, TarekkMA requested changes

2022-12-28 09:17 UTC, TarekkMA commented on pallets/domains/src/lib.rs
> +        type InitialPrices: Get<Vec<(DomainLength, BalanceOf<Self>)>>;
We need a way to grantee that this is sorted, maybe have some sort of container that checks on compile time if it's sorted and fails if not so. `const_assert`.


https://github.com/dappforce/subsocial-solochain/blob/430fe055892bfdda1b328af81b5f9792a2ee559d/runtime/src/free_calls.rs#L22-L23

https://github.com/dappforce/subsocial-solochain/blob/430fe055892bfdda1b328af81b5f9792a2ee559d/pallets/free-calls/src/config.rs#L72

2022-12-28 09:17 UTC, TarekkMA commented on pallets/domains/src/lib.rs
> +        pub fn init_pallet(default_prices: &[(DomainLength, BalanceOf<T>)]) {
Does this run, when pallet is first introduced?



Also Can we test this?

2023-03-07 17:37 UTC, Yung-Beef commented on pallets/domains/src/lib.rs
> +    pub(super) type PricesConfig<T: Config> =
Or prices. Don't know enough to comment really. What's wrong with PricesConfig?

Imo if you can't give a concrete answer, it's fine.

2023-03-24 12:24 UTC, TarekkMA reviewed
.

2023-05-30 10:12 UTC, olehmell requested changes

2023-05-30 10:57 UTC, TarekkMA commented on pallets/domains/src/lib.rs
> -            // TODO: withdraw balance when it will be possible to purchase domains.
because we transfer money to payment_beneficiary

2023-05-30 11:36 UTC, TarekkMA commented on pallets/domains/src/lib.rs
> +            owner_target: AccountIdLookupOf<T>,
what do you mean?

2023-08-18 12:38 UTC, closed without merging