Add OffChainProxy type
dappforce/subsocial-parachain pull request #175
Opened 2023-02-01 12:41 UTC by TarekkMA

Merge #174 first

2023-02-02 09:10 UTC, olehmell approved these changes

2023-02-03 10:04 UTC, F3Joule submitted a review, later dismissed

2023-02-03 10:04 UTC, F3Joule commented on runtime/src/lib.rs
> +				Call::SpaceOwnership(..)
Let's leave it as it for now. We need to rethink this - at least whether we have a further need in it.

```suggestion
				Call::Spaces(..)
					| Call::SpaceOwnership(..)
```

2023-02-07 12:41 UTC, F3Joule requested changes

2023-02-07 12:41 UTC, F3Joule commented on runtime/src/lib.rs
> +	OffChainProxy,
@Yung-Beef ?
```suggestion
	OnlyProxy,
```

2023-02-07 12:41 UTC, F3Joule commented on runtime/src/lib.rs
> +			ProxyType::OffChainProxy => {
```suggestion
			ProxyType::OnlyProxy => {
```

2023-02-08 16:53 UTC, siman approved these changes

2023-02-08 17:23 UTC, F3Joule approved these changes

2023-02-08 17:23 UTC, merged