Upgrade to polkadot-v0.9.37
dappforce/subsocial-parachain pull request #185
Opened 2023-02-15 09:05 UTC by F3Joule

### Release Checklist

- [ ] Verify `spec_version` has been incremented since the last release.
- [ ] Verify pallet and extrinsic ordering has stayed the same. Bump `transaction_version` if not.
~~Verify new extrinsics have been correctly whitelisted/blacklisted for `BaseCallFilter`.~~
~~There are benchmarks for newly created extrinsics.~~
- [ ] Verify weights have been updated for any modified runtime logic.
~~There are tests for newly created logic.~~
- [x] All the tests pass.

2023-02-15 09:05 UTC, siman commented
Task linked: [CU-861m8uhdx Upgrade parachain to the newest Substrate version](https://app.clickup.com/t/861m8uhdx)

2023-02-16 15:24 UTC, F3Joule commented
```
Metadata comparison:
Date: Thu 16 Feb 2023 17:21:53 EET
Reference: wss://para.subsocial.network
Target version: subsocial-collator 0.1.7-4e838cc0097
Chain: dev
----------------------------------------------------------------------
              [Spec] name: subsocial-parachain
                     spec_version: 19 -> 20
                     transaction_version: 3 -> 4
          [Metadata] version: 14
           [Modules] num: 31
                          [System] idx: 0 (calls: 9 -> 8, storage: 17)
                                   [-] calls: fillBlock
                                        [remark] idx: 1 -> 0 (args: 1)
                                                 (Bytes)
                                  [setHeapPages] idx: 2 -> 1 (args: 1)
                                                 (u64)
                                       [setCode] idx: 3 -> 2 (args: 1)
                                                 (Bytes)
                          [setCodeWithoutChecks] idx: 4 -> 3 (args: 1)
                                                 (Bytes)
                                    [setStorage] idx: 5 -> 4 (args: 1)
                                                 (Vec<(Bytes,Bytes)>)
                                   [killStorage] idx: 6 -> 5 (args: 1)
                                                 (Vec<Bytes>)
                                    [killPrefix] idx: 7 -> 6 (args: 2)
                                                 (Bytes, u32)
                               [remarkWithEvent] idx: 8 -> 7 (args: 1)
                                                 (Bytes)
                                   [blockWeight] type: FrameSupportWeightsPerDispatchClassU64 -> FrameSupportDispatchPerDispatchClassWeight
                 [ParachainSystem] idx: 1 (calls: 4, storage: 21 -> 22)
                                   [+] storage: lastRelayChainBlockNumber
                    [reservedXcmpWeightOverride] type: Option<u64> -> Option<SpWeightsWeightV2Weight>
                     [reservedDmpWeightOverride] type: Option<u64> -> Option<SpWeightsWeightV2Weight>
                       [Timestamp] idx: 3 (calls: 1, storage: 3)
                        [Balances] idx: 10 (calls: 6, storage: 6)
                                   [+] storage: inactiveIssuance
                                   [-] storage: storageVersion
                      [Authorship] idx: 20 (calls: 1, storage: 4)
               [CollatorSelection] idx: 21 (calls: 5, storage: 6)
                         [Session] idx: 22 (calls: 2, storage: 8)
                         [Vesting] idx: 26 (calls: 5, storage: 3)
                           [Proxy] idx: 27 (calls: 10, storage: 3)
                                   [+] calls: createPure, killPure
                                   [-] calls: anonymous, killAnonymous
                                         [proxy] idx: 0 (args: 3)
                                                 (AccountId32, Option<SubsocialParachainRuntimeProxyType>, Call) -> (MultiAddress, Option<SubsocialParachainRuntimeProxyType>, Call)
                                      [addProxy] idx: 1 (args: 3)
                                                 (AccountId32, SubsocialParachainRuntimeProxyType, u32) -> (MultiAddress, SubsocialParachainRuntimeProxyType, u32)
                                   [removeProxy] idx: 2 (args: 3)
                                                 (AccountId32, SubsocialParachainRuntimeProxyType, u32) -> (MultiAddress, SubsocialParachainRuntimeProxyType, u32)
                                      [announce] idx: 6 (args: 2)
                                                 (AccountId32, H256) -> (MultiAddress, H256)
                            [removeAnnouncement] idx: 7 (args: 2)
                                                 (AccountId32, H256) -> (MultiAddress, H256)
                            [rejectAnnouncement] idx: 8 (args: 2)
                                                 (AccountId32, H256) -> (MultiAddress, H256)
                                [proxyAnnounced] idx: 9 (args: 4)
                                                 (AccountId32, AccountId32, Option<SubsocialParachainRuntimeProxyType>, Call) -> (MultiAddress, MultiAddress, Option<SubsocialParachainRuntimeProxyType>, Call)
                       [XcmpQueue] idx: 30 (calls: 9, storage: 10)
                        [DmpQueue] idx: 33 (calls: 1, storage: 5)
                         [Domains] idx: 60 (calls: 8, storage: 6)
                          [Energy] idx: 61 (calls: 2, storage: 4)
                           [Roles] idx: 71 (calls: 8, storage: 6)
                  [AccountFollows] idx: 72 (calls: 3, storage: 4)
                        [Profiles] idx: 73 (calls: 3, storage: 2)
                    [SpaceFollows] idx: 74 (calls: 3, storage: 4)
                  [SpaceOwnership] idx: 75 (calls: 3, storage: 2)
                          [Spaces] idx: 76 (calls: 4, storage: 4)
                           [Posts] idx: 77 (calls: 6, storage: 6)
                       [Reactions] idx: 78 (calls: 6, storage: 5)
                            [Sudo] idx: 255 (calls: 4, storage: 2)
                           [sudoUncheckedWeight] idx: 1 (args: 2)
                                                 (Call, u64) -> (Call, SpWeightsWeightV2Weight)

------------------------------ SUMMARY ------------------------------- 
⚠️ This filter is here to help spotting changes that should be reviewed carefully. 
⚠️ It catches only index changes, deletions and value decreases. 
## Deletions
 13: [-] calls: fillBlock
38: [-] storage: storageVersion
45: [-] calls: anonymous, killAnonymous

## Index changes
 14: [remark] idx: 1 -> 0 (args: 1)
16: [setHeapPages] idx: 2 -> 1 (args: 1)
18: [setCode] idx: 3 -> 2 (args: 1)
20: [setCodeWithoutChecks] idx: 4 -> 3 (args: 1)
22: [setStorage] idx: 5 -> 4 (args: 1)
24: [killStorage] idx: 6 -> 5 (args: 1)
26: [killPrefix] idx: 7 -> 6 (args: 2)
28: [remarkWithEvent] idx: 8 -> 7 (args: 1)

## Decreases
```

2023-02-16 17:06 UTC, TarekkMA approved these changes
LGTM

2023-02-28 16:57 UTC, siman requested changes

2023-03-02 17:23 UTC, siman approved these changes

2023-03-02 17:24 UTC, merged