Added copyright action & texts in all files
dappforce/subsocial-parachain pull request #219
Opened 2023-06-26 04:35 UTC by tusharojha

The actual script to compare the copyright text in a file is extracted to another package at [tusharojha/copyright-check](https://github.com/tusharojha/copyright-check). 

We can:
- move the github repo for the action to dappforce 
- OR, I release a version on github marketplace and use it (might take some time to review 1-2 day)

2023-06-27 13:05 UTC, olehmell commented on copyright.txt
> +// Copyright (C) 2021-2022 DAPPFORCE PTE. Ltd., aleksandr.siman@gmail.com.
```suggestion
// Copyright (C) 2021-2023 DAPPFORCE PTE. Ltd., aleksandr.siman@gmail.com.
```

2023-06-28 11:30 UTC, tusharojha commented on copyright.txt
> +// Copyright (C) 2021-2022 DAPPFORCE PTE. Ltd., aleksandr.siman@gmail.com.
@olehmell done

2023-06-28 11:34 UTC, olehmell commented
I will move it to our dappforce repo today

2023-08-01 15:33 UTC, olehmell requested changes

2023-08-01 15:33 UTC, olehmell commented on copyright.txt
> +// Copyright (C) 2021-2023 DAPPFORCE PTE. Ltd., dappforce@gmail.com.
```suggestion
// Copyright (C) DAPPFORCE PTE. LTD., dappforce@gmail.com.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0.
```

2023-10-30 22:11 UTC, F3Joule commented
Replaced with #239

2023-10-30 22:11 UTC, closed without merging