Add prices configs to domains pallet
dappforce/subsocial-parachain pull request #221
Opened 2023-07-13 11:02 UTC by F3Joule

This also removes `MaxPromoDomainsPerAccount`

2023-07-13 13:24 UTC, siman requested changes

2023-07-13 13:24 UTC, siman commented on pallets/domains/src/lib.rs
> +            PricesConfig::<T>::set(new_prices_config);
Extract to `fn do_set_prices_config()` and reuse in the `GenesisBuild` instead of `Pallet::<T>::init_pallet(...)`.

2023-07-13 13:24 UTC, siman commented on pallets/domains/src/lib.rs
> +        pub fn init_pallet(default_prices: &[(DomainLength, BalanceOf<T>)]) {
Get rid of this fn. Use `do_set_prices_config()` instead.

2023-08-01 10:35 UTC, siman approved these changes

2023-08-01 10:54 UTC, olehmell approved these changes

2023-08-01 11:53 UTC, merged