Add custom RPCs to creator staking
dappforce/subsocial-parachain pull request #231
Opened 2023-09-13 07:12 UTC by F3Joule

2023-09-14 11:25 UTC, olehmell requested changes

2023-09-14 11:25 UTC, olehmell commented on pallets/creator-staking/src/functions.rs
> +                available_claims_by_creator.entry(creator).and_modify(|e| *e += 1).or_insert(1);
So here we are calculating how many times/eras we can claim. So if we have [(1, 5), (2, 10)] on response, on UI we will put claim for the creator #1 - 5 times and for #2 - 10 times, right?

2023-09-14 11:25 UTC, olehmell commented on pallets/creator-staking/src/functions.rs
> +                available_claims_by_creator.entry(creator).and_modify(|e| *e += 1).or_insert(1);
Pretty hard understand from name what does mean the `u32` in response. So maybe "available_claim_count_by_creator"

2023-09-14 11:25 UTC, olehmell commented on pallets/creator-staking/rpc/src/lib.rs
> +    /// Creates a new instance of the Domains Rpc helper.
```suggestion
    /// Creates a new instance of the CreatorStaking Rpc helper.
```

2023-09-14 11:25 UTC, olehmell commented on pallets/creator-staking/src/functions.rs
> +            }
Same block code on 392-397 lines. Not sure that we can optimize it, but wanted to notify

2023-09-14 11:25 UTC, olehmell commented on pallets/creator-staking/src/functions.rs
> +                if era >= unregistered_era || era == 0 {
You are using same condition in `available_claims_by_staker`, so maybe make sense to extract it

2023-09-14 11:25 UTC, olehmell commented on pallets/creator-staking/src/functions.rs
> +                    Self::calculate_reward_for_staker_in_era(&creator_stake_info, staked, era)
if we have `default` value for `creator_stake_info` here, does make sense to call calculate function anyway?

2023-09-14 11:28 UTC, olehmell commented on pallets/creator-staking/rpc/src/lib.rs
> +/// Provides RPC method to query a domain price.
Update comment

2023-09-14 11:28 UTC, olehmell commented on pallets/creator-staking/rpc/src/lib.rs
> +//! RPC interface for the domains pallet.
```suggestion
//! RPC interface for the creator-staking pallet.
```

2023-09-18 07:55 UTC, F3Joule commented on pallets/creator-staking/Cargo.toml
> +version = "0.1.8"
Yeah, good for now. We'll bump crates version to 0.1.9 because of this RPC.

2023-10-21 07:37 UTC, merged