Apply suggestions after creator staking code review
dappforce/subsocial-parachain pull request #232
Opened 2023-09-13 07:13 UTC by F3Joule

2023-09-14 12:13 UTC, olehmell requested changes

2023-09-14 12:13 UTC, olehmell commented on pallets/creator-staking/src/types/mod.rs
>      pub total: Balance,
In conversation you said that renamed it to "StakesInfo", but you renamed "StakesInfo" to "StakesInfoOf" in the PR. I am confused :)

2023-09-19 10:33 UTC, siman commented on pallets/creator-staking/src/types/impls.rs
> +    /// Stakes some value in the specified era.
```suggestion
    /// Increase existing stake in the specified era.
```

2023-09-19 10:35 UTC, siman commented on pallets/creator-staking/src/types/impls.rs
> +    /// latest available era in the staking info.
```suggestion
    /// latest available era in the `StakesInfo`.
```

2023-09-19 10:38 UTC, siman commented on pallets/creator-staking/src/types/impls.rs
>      /// Unstakes some value in the specified era.
```suggestion
    /// Decrease existing stake in the specified era.
```

2023-09-19 10:38 UTC, siman commented on pallets/creator-staking/src/types/impls.rs
>      /// Unstakes some value in the specified era.
Also update `staking info` to ``StakesInfo``

2023-09-19 10:38 UTC, siman commented on pallets/creator-staking/src/types/impls.rs
>      pub(crate) fn unstake(&mut self, current_era: EraIndex, value: Balance) -> Result<(), &str> {
```suggestion
    pub(crate) fn decrease_stake(&mut self, current_era: EraIndex, value: Balance) -> Result<(), &str> {
```

2023-09-19 10:39 UTC, siman commented on pallets/creator-staking/src/types/impls.rs
> +    /// The following example demonstrates how internal vector changes when `stake` is called:
```suggestion
    /// The following example demonstrates how internal vector changes when `increase_stake()` is called:
```

2023-09-19 10:39 UTC, siman commented on pallets/creator-staking/src/types/impls.rs
> +    /// * `stake(9, 200)` will result in `[<5, 1000>, <7, 1400>, <9, 1600>]`
```suggestion
    /// `increase_stake: [<5, 1000>, <7, 1300>]`
    /// * `increase_stake(7, 100)` will result in `[<5, 1000>, <7, 1400>]`
    /// * `increase_stake(9, 200)` will result in `[<5, 1000>, <7, 1400>, <9, 1600>]`
```

2023-09-19 10:51 UTC, siman commented on pallets/creator-staking/src/types/impls.rs
> +    /// * `stake(9, 200)` will result in `[<5, 1000>, <7, 1400>, <9, 1600>]`
```suggestion
    /// * `increase_stake(7, 100)` will result in `[<5, 1000>, <7, 1400>]`
    /// * `increase_stake(9, 200)` will result in `[<5, 1000>, <7, 1400>, <9, 1600>]`
```

2023-09-19 11:02 UTC, siman commented on pallets/creator-staking/src/lib.rs
>          /// an additional `EraStake` value by calling `bond() & stake()` or `unbond() & unstake()` if they've
Get rid of `bond()` in docs. We do not have it anymore.

2023-09-20 15:03 UTC, siman commented on pallets/creator-staking/src/functions.rs
>          ensure!(
Add a comment why we do this check after corrections to the stake amount

2023-09-20 15:52 UTC, siman commented on pallets/creator-staking/src/inflation.rs
> +        let (fixed_treasury_imbalance, treasury_imbalance) = remainder.split(treasury_balance);
Please give better names to these two treasury balances

2023-09-27 08:47 UTC, siman requested changes

2023-09-27 08:47 UTC, siman commented on pallets/creator-staking/src/lib.rs
> +        type MinimumRemainingFreeBalance: Get<BalanceOf<Self>>;
Some storages in this pallet are called `Max***` but others `Minimum***`. I mean the short versions of the word vs the long version of the similar word.

2023-10-16 13:23 UTC, siman approved these changes

2023-10-18 23:26 UTC, merged