Add Treasury to the parachain runtime
dappforce/subsocial-parachain pull request #24
Opened 2022-02-22 14:47 UTC by F3Joule

### Release Checklist

- [ ] Verify `spec_version` has been incremented since the last release.
- [ ] Verify pallet and extrinsic ordering has stayed the same. Bump `transaction_version` if not.
- [ ] Verify new extrinsics have been correctly whitelisted/blacklisted for `BaseCallFilter`.
- [ ] Verify benchmarks have been updated for any modified runtime logic.

2022-03-03 17:38 UTC, siman requested changes

2022-03-03 17:38 UTC, siman commented on runtime/src/lib.rs
> +	pub ProposalBondMaximum: Balance = 40_000 * UNIT;
```suggestion
	pub ProposalBondMinimum: Balance = 100 * UNIT;
	pub ProposalBondMaximum: Balance = 500 * UNIT;
```

2022-03-03 17:38 UTC, siman commented on runtime/src/lib.rs
> +		Treasury: pallet_treasury = 17,
```suggestion
		Treasury: pallet_treasury = 15,
```

2023-12-28 13:10 UTC, F3Joule commented
Newer PR exists #249

2023-12-28 13:10 UTC, closed without merging