Add an ability to use real account energy for proxy
dappforce/subsocial-parachain pull request #260
Opened 2024-03-29 12:06 UTC by F3Joule

2024-03-29 15:17 UTC, siman requested changes

2024-03-29 15:17 UTC, siman commented on pallets/energy/src/lib.rs
> +            let energy_consumer = match <T as Config>::RuntimeCall::from_ref(call).is_sub_type() {
```suggestion
            let maybe_proxy_call = <T as Config>::RuntimeCall::from_ref(call).is_sub_type();
            let energy_provider = match maybe_proxy_call {
```

2024-03-29 15:17 UTC, siman commented on pallets/energy/src/lib.rs
> +                    if pallet_proxy::Pallet::<T>::find_proxy(&real_account, who, None).is_ok() {
```suggestion
                    let is_who_a_proxy = pallet_proxy::Pallet::<T>::find_proxy(&real_account, who, None).is_ok();
                    if is_who_a_proxy {
```

2024-04-02 14:33 UTC, olehmell requested changes

2024-04-09 14:09 UTC, siman approved these changes

2024-04-09 14:12 UTC, olehmell approved these changes

2024-04-09 15:34 UTC, merged