Update README.md
dappforce/subsocial-parachain pull request #34
Opened 2022-04-11 10:09 UTC by F3Joule

2022-04-11 13:07 UTC, Yung-Beef commented on README.md
> +Simple run and join the network with docker:
Simply

2022-04-11 13:07 UTC, Yung-Beef commented on README.md
> +Official docker hub image of Subsocial parachain: https://hub.docker.com/r/dappforce/subsocial-parachain
the Subsocial parachain

2022-04-12 18:08 UTC, siman requested changes

2022-04-12 18:08 UTC, siman commented on README.md
> +For linux, FreeBSD, OpenBSD and macOS:
```suggestion
For Linux, FreeBSD, OpenBSD, and macOS:
```

2022-04-12 18:08 UTC, siman commented on README.md
> +Official docker hub image of the Subsocial parachain: https://hub.docker.com/r/dappforce/subsocial-parachain
```suggestion
Official Docker Hub image of the Subsocial parachain: https://hub.docker.com/r/dappforce/subsocial-parachain
```

2022-04-12 20:55 UTC, siman approved these changes

2022-04-12 20:56 UTC, merged