Improve domains readme
dappforce/subsocial-parachain pull request #40
Opened 2022-04-20 22:50 UTC by siman

2022-04-20 23:21 UTC, TarekkMA approved these changes

2022-04-21 10:51 UTC, F3Joule requested changes

2022-04-21 10:51 UTC, F3Joule commented on pallets/domains/README.md
> +  Metadata associated per domain.
```suggestion
  Metadata associated with domain.
```

2022-04-21 10:51 UTC, F3Joule commented on pallets/domains/README.md
> +  Domains owned per account.
```suggestion
  Domains owned by account.
```

2022-05-17 19:09 UTC, F3Joule approved these changes

2022-05-17 19:09 UTC, merged