Extract space-follows tests from integration-test
dappforce/subsocial-parachain pull request #81
Opened 2022-06-30 08:38 UTC by TarekkMA

based on #74

2022-09-15 11:24 UTC, F3Joule requested changes

2022-09-15 11:24 UTC, F3Joule commented on pallets/space-follows/tests/src/mock.rs
> +        Profiles: pallet_profiles,
```suggestion
```

2022-09-15 11:24 UTC, F3Joule commented on pallets/space-follows/tests/src/mock.rs
> +        Posts: pallet_posts,
```suggestion
```

2022-09-15 11:24 UTC, F3Joule commented on pallets/space-follows/tests/src/mock.rs
> +
```suggestion
```

2022-09-15 11:24 UTC, F3Joule commented on pallets/space-follows/tests/src/mock.rs
> +    type IsContentBlocked = MockModeration;
```suggestion
    type IsAccountBlocked = ();
    type IsContentBlocked = ();
```

2022-09-15 11:24 UTC, F3Joule commented on pallets/space-follows/tests/src/mock.rs
> +
```suggestion
```

2022-09-15 11:24 UTC, F3Joule commented on pallets/space-follows/tests/src/mock.rs
> +    type IsContentBlocked = MockModeration;
```suggestion
    type IsAccountBlocked = ();
    type IsContentBlocked = ();
```

2022-09-15 11:24 UTC, F3Joule commented on pallets/space-follows/tests/src/tests.rs
> +            vec![ACCOUNT1, ACCOUNT2]
We don't auto-follow space by space owner anymore:

```suggestion
            vec![ACCOUNT2]
```

2022-09-15 11:24 UTC, F3Joule commented on pallets/space-follows/tests/src/tests.rs
> +        );
```suggestion
        assert!(SpaceFollows::space_followed_by_account((ACCOUNT2, SPACE1)));
```

2022-09-15 11:24 UTC, F3Joule commented on pallets/space-follows/tests/src/tests.rs
> +        ));
```suggestion
        assert_ok!(_update_space(None, None, Some(space_update(None, Some(true)))));
```

2022-09-15 11:24 UTC, F3Joule commented on pallets/space-follows/tests/src/tests.rs
> +        assert_eq!(SpaceFollows::space_followers(SPACE1), vec![ACCOUNT1]);
```suggestion
        assert!(SpaceFollows::space_followers(SPACE1).is_empty());
```

2022-09-15 12:50 UTC, siman requested changes

2022-09-15 13:52 UTC, TarekkMA commented on pallets/space-follows/tests/src/tests_utils.rs
> +use frame_support::assert_ok;
I'm not refactoring any code, just copying from integration-test

2022-09-19 09:45 UTC, F3Joule approved these changes

2022-12-21 11:31 UTC, F3Joule approved these changes

2022-12-21 11:32 UTC, F3Joule commented on pallets/space-follows/tests/Cargo.toml
> +scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
```suggestion
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
```

2022-12-21 11:34 UTC, olehmell approved these changes

2022-12-23 13:20 UTC, siman requested changes

2022-12-23 13:20 UTC, siman commented on pallets/space-follows/tests/src/tests_utils.rs
> +pub(crate) fn _create_subspace(
We don't have subspace functionality

2022-12-23 13:20 UTC, siman commented on pallets/space-follows/tests/src/tests_utils.rs
> +pub(crate) fn _create_space_with_parent_id(
We don't have parent space functionality

2022-12-23 13:36 UTC, siman approved these changes

2022-12-27 13:13 UTC, merged