Add reactions benchmarks
dappforce/subsocial-parachain pull request #98
Opened 2022-07-07 14:02 UTC by TarekkMA

2023-01-25 15:41 UTC, F3Joule requested changes

2023-01-25 15:41 UTC, F3Joule commented on integration-tests/src/mock.rs
> +    type WeightInfo = pallet_reactions::weights::SubstrateWeight<TestRuntime>;
```suggestion
    type WeightInfo = ();
```

2023-01-25 15:41 UTC, F3Joule commented on pallets/reactions/Cargo.toml
> +runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
```suggestion
runtime-benchmarks = ['frame-benchmarking/runtime-benchmarks']
```

2023-01-25 15:41 UTC, F3Joule commented on pallets/reactions/Cargo.toml
> +try-runtime = ["frame-support/try-runtime"]
```suggestion
try-runtime = ['frame-support/try-runtime']
```

2023-01-25 15:41 UTC, F3Joule commented on pallets/reactions/Cargo.toml
> +frame-benchmarking = { optional = true, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.24", default-features = false }
```suggestion
frame-benchmarking = { git = 'https://github.com/paritytech/substrate', branch = 'polkadot-v0.9.24', default-features = false, optional = true }
```

2023-01-25 15:42 UTC, F3Joule approved these changes

2023-01-26 15:18 UTC, olehmell approved these changes

2023-01-26 15:18 UTC, olehmell commented on pallets/reactions/src/benchmarking.rs
> +                .expect("Reaction not found")
I believe that we should improve the description for test.

Maybe 
First: "Reaction is not found by postId."
Seconde: "Reaction is not found."

2023-01-26 16:08 UTC, merged